### ISSUE TITLE
index.html内のTwitter IDにリンクを貼る

### ISSUE THREAD

**Issue by suginoy** [hirocaster/wdpress69#307]
せっかく記名してもらっている方がいるので。
Pull Req.の時にメンションで本人に通知してマージしてもらう。

**Comment by sue445** [comment]
> Pull Req.の時にメンションで本人に通知してマージしてもらう。

これだとPR対応する人に依存するのでオートリンクした方がいいかなぁと思いました。
jsでサクッと実装できたので別途PR投げます

ちなみに昔公式でこんな機能が提供されてたなぁと思ったら既に廃止されてましたorz
https://dev.twitter.com/docs/anywhere/welcome
